#6 Save users in database with default role guest
reqiii/arctgkolbasy pull request #10
Opened 2022-12-16 14:18 UTC by reqiii

2022-12-16 14:29 UTC, deradot22 commented on src/main/kotlin/org/arctgkolbasy/bot/user/User.kt
> +data class User (
odd space

2022-12-16 14:30 UTC, DimaZet requested changes
Looks good to me but few naming fixes needed

2022-12-16 14:30 UTC, DimaZet commented on src/main/kotlin/org/arctgkolbasy/bot/user/model/Roles.kt
> +class Roles (
rename class name ```Roles``` to ```Role``` please

2022-12-16 14:30 UTC, DimaZet commented on src/main/resources/db/migration/changesets/1-create-tables.sql
>  create table if not exists products (
rename please tables 'consumer' and 'users_to_role' to 'consumers' and 'users_to_roles'

2022-12-17 23:15 UTC, DimaZet approved these changes

2022-12-17 23:16 UTC, merged